# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a3526a132307218130d6db630fe894ea08dccbf87ef4669ce0784adfa1f36673c27e50af6a8532cb66bd12ef37b93056ad73b7d0e901796eaf45186aba0cfca

test:
  secret_key_base: b3c129870c7206907c6f410505ee2840f70c055bebda6fe00079d4ae4e12784cc12f7f155a908689ba0aa29b9d274bd7d37183ea04c10414bce9ed84f8605e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
